steps:
  - bash: |
      set -e
      curl -Os https://cli.codecov.io/latest/linux/codecov
      chmod +x codecov
      echo "Starting Codecov Upload"

      # Allow Codecov failures without failing the job
      set +e
      if [ -n "${CODECOV_TOKEN:-}" ]; then
        ./codecov --verbose upload-process --token "${CODECOV_TOKEN}" --dir .
      else
        ./codecov --verbose upload-process --dir .
      fi
      CODECOV_EXIT=$?
      set -e

      if [ "$CODECOV_EXIT" -ne 0 ]; then
        echo "Codecov upload failed with exit code ${CODECOV_EXIT}, continuing without failing the job."
      fi

      echo "Codecov Upload Complete"
    retryCountOnTaskFailure: 1
    displayName: Upload Coverage Report To Codecov.io
    condition: succeededOrFailed()
